# Generated by Django 4.2.5 on 2023-09-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Weathers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('temp', models.FloatField()),
                ('description', models.TextField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('date_now', models.TextField()),
                ('sun_rise', models.TextField()),
                ('sun_set', models.TextField()),
                ('cur_sunset', models.TextField()),
                ('cur_sunrise', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weather.categories')),
            ],
        ),
    ]
