# Generated by Django 4.2.5 on 2023-09-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_country',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
